name: Build & Push Docker Image (multi-platform)

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: downward-api
  REGISTRY: ghcr.io
  FULL_IMAGE: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}

jobs:
  build:
    runs-on: self-hosted  # 또는 ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      # ✅ GITHUB_TOKEN → GHCR_PAT 로 변경
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.FULL_IMAGE }}:latest